export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";


export const ADD_FACILITIES = 'ADD_FACILITIES';
export const DELETE_FACILITIES = 'DELETE_FACILITIES';
export const UPDATE_FACILITIES = 'UPDATE_FACILITIES';
export const LOADING_FACILITIES = 'LOADING_FACILITIES';
export const GET_FACILITIES = 'GET_FACILITIES';


export const ADD_PRODUCTES = 'ADD_PRODUCTES';
export const DELETE_PRODUCTES = 'DELETE_PRODUCTES';
export const UPDATE_PRODUCTES = 'UPDATE_PRODUCTES';
export const LOADING_PRODUCTES = 'LOADING_PRODUCTES';
export const GET_PRODUCTES = 'GET_PRODUCTES';
export const ERROR_PRODUCTES = 'ERROR_PRODUCTES';

export const GET_SHOP = "GET_SHOP";

export const GET_REVIEW = "GET_REVIEW";
export const ADD_REVIEW = 'ADD_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const LOADING_REVIEW = 'LOADING_REVIEW';
export const ERROR_REVIEW = 'ERROR_REVIEW';

export const ADD_TO_CART = 'ADD_TO_CART';

export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';